name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Read version
        id: version
        run: |
          $version = ([xml](Get-Content HtmlToOmtCli.csproj)).Project.PropertyGroup.Version
          echo "value=v$version" >> $env:GITHUB_OUTPUT

      - name: Publish
        run: dotnet publish -c Release -r win-x64 --self-contained true -o publish

      - name: Zip
        run: Compress-Archive -Path publish\* -DestinationPath HtmlToOmtCli-win-x64.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.value }}
          name: ${{ steps.version.outputs.value }}
          files: HtmlToOmtCli-win-x64.zip
          body: |
            ## Requirements
            - [Visual C++ Redistributable 2019+](https://aka.ms/vs/17/release/vc_redist.x64.exe)

            ## Usage
            ```
            HtmlToOmtCli <url> [source-name] [width] [height] [fps]
            ```
